name: Android CI – AntiDebug

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 8 (for Gradle)
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '8'

    - name: Make gradlew executable
      run: chmod +x AntiDebug/gradlew

    - name: Install required Android SDK packages
      run: |
        echo "y" | /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager \
          "platforms;android-26" \
          "platform-tools" \
          "build-tools;26.0.3" \
          "ndk;21.4.7075529" \
          "cmake;3.10.2.4988404"

    - name: Build Debug APK
      working-directory: AntiDebug
      run: ./gradlew assembleDebug

    - name: Build Release APK
      working-directory: AntiDebug
      run: ./gradlew assembleRelease

    - name: Upload APKs
      uses: actions/upload-artifact@v4
      with:
        name: AntiDebug-apks
        path: |
          AntiDebug/app/build/outputs/apk/debug/*.apk
          AntiDebug/app/build/outputs/apk/release/*.apk
